/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.EnterpriseAccessAdmin;

import Model.Travel;
import static Utilities.Validations.validatePassword;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author minal
 */
public class SetAccessEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SetAccessEnterpriseJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    private String role;
    public SetAccessEnterpriseJPanel(JPanel userProcessContainer, Travel travel, String role) {
        initComponents();
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.role = role;
        lblUpdateHeader.setText("Update Admin Access for "+role);
        if(role == "Government Personnel"){
            txtUsername.setText(travel.getGovBoaAdmin().getUsername());
            txtPassword.setText(travel.getGovBoaAdmin().getPassword());
        }
        else if(role == "Transportation Board Personnel"){
            txtUsername.setText(travel.getTraBoaAdmin().getUsername());
            txtPassword.setText(travel.getTraBoaAdmin().getPassword());
        }
        else if(role == "Hotel Board Personnel"){
            txtUsername.setText(travel.getHotelAdmin().getUsername());
            txtPassword.setText(travel.getHotelAdmin().getPassword());
        }
        else if(role == "Local Business Board Personnel"){
            txtUsername.setText(travel.getLocalbuAdmim().getUsername());
            txtPassword.setText(travel.getLocalbuAdmim().getPassword());   
        }
        else if(role == "Travel Agency Board Personnel"){
            txtUsername.setText(travel.getTravelABoaAdmin().getUsername());
            txtPassword.setText(travel.getTravelABoaAdmin().getPassword());   
        }
        else{
            txtUsername.setText(travel.getFinManAdmin().getUsername());
            txtPassword.setText(travel.getFinManAdmin().getPassword());
        }
        txtPassword.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdateHeader = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblUpdatePassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        lblUpdateHeader.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblUpdateHeader.setText("Update Admin Access");

        lblUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUsername.setText("Username:");

        lblUpdatePassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUpdatePassword.setText("Password:");

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtUsername.setEnabled(false);

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUpdateHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblUpdateHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtPassword.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String inputPassword = new String(txtPassword.getPassword());
        if(inputPassword.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please check if password field is filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(validatePassword(inputPassword)){
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one digit.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String salt = BCrypt.gensalt();
        String cPassword = BCrypt.hashpw(inputPassword, salt);
        if(role == "Government Personnel")
        travel.getGovBoaAdmin().setPassword(cPassword);
        else if(role == "Transportation Board Personnel")
        travel.getTraBoaAdmin().setPassword(cPassword);
        else if(role == "Hotel Board Personnel")
        travel.getHotelAdmin().setPassword(cPassword);
        else if(role == "Financial Manager")
        travel.getFinManAdmin().setPassword(cPassword);
        else if(role == "Local Business Board Personnel")
        travel.getLocalbuAdmim().setPassword(cPassword);
        else
        travel.getTravelABoaAdmin().setPassword(cPassword);
        JOptionPane.showMessageDialog(this, "Password updated successfuly!");
        txtPassword.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblUpdateHeader;
    private javax.swing.JLabel lblUpdatePassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
