/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.OrganizationsManage;

import Model.Hotel.Hotel;
import Model.LocalBusiness.LocalBusiness;
import Model.Organizations.Organization;
import Model.TransportAgency.TransportAgency;
import Model.Travel;
import Model.TravelAgency.TravelAgency;
import static Utilities.Validations.validateEmail;
import static Utilities.Validations.validateName;
import static Utilities.Validations.validatePassword;
import static Utilities.Validations.validatePhone;
import static Utilities.Validations.validateUsername;
import com.itextpdf.text.log.Logger;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.lang.System.Logger.Level;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrutidixit
 */
public class AddOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddOrganizationJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    private String org;
    private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;

    public AddOrganizationJPanel(JPanel userProcessContainer, Travel travel, String org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.org = org;
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        if (org.equals("Transport Agency")) {
            model.addElement("Road");
            model.addElement("Rail");
            model.addElement("Sea");
            model.addElement("Air");
        } else if (org.equals("Government")) {
            model.addElement("Hotel");
            model.addElement("Travel Agency");
            model.addElement("Local Business");
        }
        optionsType.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrgHeader = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtHq = new javax.swing.JTextField();
        lblHq = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        lblManagerName = new javax.swing.JLabel();
        txtManagerEmail = new javax.swing.JTextField();
        lblManagerEmail = new javax.swing.JLabel();
        txtManagerContact = new javax.swing.JTextField();
        lblManagerContact = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        optionsType = new javax.swing.JComboBox<>();
        imgLogo = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrgHeader.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        lblOrgHeader.setText("Add Organization type:");
        add(lblOrgHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 510, 50));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        lblUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 220, 40));

        txtUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 220, 40));

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 220, 40));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 100, 30));

        txtDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 220, 40));

        lblDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblDescription.setText("Description:");
        add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        txtHq.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtHq, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 220, 40));

        lblHq.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblHq.setText("Location Headquarters:");
        add(lblHq, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        txtManagerName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 220, 40));

        lblManagerName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerName.setText("Manager Name:");
        add(lblManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        txtManagerEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtManagerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 220, 40));

        lblManagerEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerEmail.setText("Manager Email:");
        add(lblManagerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        txtManagerContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtManagerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 220, 40));

        lblManagerContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerContact.setText("Manager Contact:");
        add(lblManagerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 90, -1));

        lblLogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblLogo.setText("Logo:");
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, -1, -1));

        lblType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblType.setText("Type:");
        add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, -1));

        optionsType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(optionsType, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 220, 40));

        imgLogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 158, 150));

        btnAttach.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });
        add(btnAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 90, -1));

        btnRemove.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 260, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 88, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            URL url;
            try {
                url = file.toURI().toURL();
                logoImage = new ImageIcon(url);
                logoImage = new ImageIcon(logoImage.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH));
                imgLogo.setIcon(logoImage);
            } catch (MalformedURLException ex) {
                java.util.logging.Logger.getLogger(this.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        logoImage = null;
        imgLogo.setIcon(logoImage);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String oName = txtName.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String description = txtDescription.getText();
        String headquarters = txtHq.getText();
        String mName = txtManagerName.getText();
        String mEmail = txtManagerEmail.getText();
        String mContact = txtManagerContact.getText();
        String type = optionsType.getSelectedItem().toString();

        if (oName.isEmpty() || username.isEmpty() || password.isEmpty() || description.isEmpty() || headquarters.isEmpty() || mName.isEmpty() || mEmail.isEmpty() || mContact.isEmpty() || type.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (validateName(mName)) {
            JOptionPane.showMessageDialog(this, "Name should be between 5 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (validateUsername(username)) {
            JOptionPane.showMessageDialog(this, "Username should be between 5 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (validatePhone(mContact)) {
            JOptionPane.showMessageDialog(this, "Please verify if Phone number is in correct format \"(000) 000-0000\"", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (validateEmail(mEmail)) {
            JOptionPane.showMessageDialog(this, "Please verify if email is in correct format \"youremail@xxx.xxx\"", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (validatePassword(password)) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one digit.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Map<String, String> loginCredentials = new HashMap<>();
        loginCredentials.put(username, password);

        if (type.equals("Hotel")) {
            for (Hotel hotel : travel.getHotelDirectory().getHotelList()) {
                if (hotel.getBusinessName().equals(oName) && hotel.getType().equals(type)) {
                    JOptionPane.showMessageDialog(this, "Hotel Name already exits in this type. Please try with a new one.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            travel.getHotelDirectory().addHodel(oName, description, loginCredentials, headquarters, mName, mContact, mEmail, type, logoImage);
        }

        if (type.equals("Local Business")) {
            for (LocalBusiness localBusiness : travel.getLocalBusinessDirectory().getLocalBusinessList()) {
                if (localBusiness.getBusinessName().equals(oName) && localBusiness.getType().equals(type)) {
                    JOptionPane.showMessageDialog(this, "Local Business Name already exits in this type. Please try with a new one.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            travel.getLocalBusinessDirectory().addLocalBusiness(oName, description, loginCredentials, headquarters, mName, mContact, mEmail, type, logoImage);
        }

        if (type.equals("Air")) {
            for (TransportAgency transportAgency : travel.getTrnsportAgencyDirectory().getTransporAgencyList()) {
                if (transportAgency.getBusinessName().equals(oName) && transportAgency.getType().equals(type)) {
                    JOptionPane.showMessageDialog(this, "Transport Agency Name already exits in this type. Please try with a new one.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            travel.getTrnsportAgencyDirectory().addTransporAgency(oName, description, loginCredentials, headquarters, mName, mContact, mEmail, type, logoImage, "Air");
        }

        if (type.equals("Road")) {
            for (TransportAgency transportAgency : travel.getTrnsportAgencyDirectory().getTransporAgencyList()) {
                if (transportAgency.getBusinessName().equals(oName) && transportAgency.getType().equals(type)) {
                    JOptionPane.showMessageDialog(this, "Transport Agency Name already exits in this type. Please try with a new one.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            travel.getTrnsportAgencyDirectory().addTransporAgency(oName, description, loginCredentials, headquarters, mName, mContact, mEmail, type, logoImage, "Road");
        }

        if (type.equals("Rail")) {
            for (TransportAgency transportAgency : travel.getTrnsportAgencyDirectory().getTransporAgencyList()) {
                if (transportAgency.getBusinessName().equals(oName) && transportAgency.getType().equals(type)) {
                    JOptionPane.showMessageDialog(this, "Transport Agency Name already exits in this type. Please try with a new one.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            travel.getTrnsportAgencyDirectory().addTransporAgency(oName, description, loginCredentials, headquarters, mName, mContact, mEmail, type, logoImage, "Rail");
        }

        if (type.equals("Sea")) {
            for (TransportAgency transportAgency : travel.getTrnsportAgencyDirectory().getTransporAgencyList()) {
                if (transportAgency.getBusinessName().equals(oName) && transportAgency.getType().equals(type)) {
                    JOptionPane.showMessageDialog(this, "Transport Agency Name already exits in this type. Please try with a new one.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            travel.getTrnsportAgencyDirectory().addTransporAgency(oName, description, loginCredentials, headquarters, mName, mContact, mEmail, type, logoImage, "Sea");
        }

        if (type.equals("Travel Agency")) {
            for (TravelAgency travelAgency : travel.getTravelAgencyDirectory().getTravelAgencyList()) {
                if (travelAgency.getBusinessName().equals(oName) && travelAgency.getType().equals(type)) {
                    JOptionPane.showMessageDialog(this, "Travel Agency Name already exits in this type. Please try with a new one.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            travel.getTravelAgencyDirectory().addTravelAgency(oName, description, loginCredentials, headquarters, mName, mContact, mEmail, type, logoImage);
        }        
        
        JOptionPane.showMessageDialog(this, "Organization registered successfuly!");
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtDescription.setText("");
        txtHq.setText("");
        txtManagerName.setText("");
        txtManagerEmail.setText("");
        txtManagerContact.setText("");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblHq;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblManagerContact;
    private javax.swing.JLabel lblManagerEmail;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrgHeader;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JComboBox<String> optionsType;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtHq;
    private javax.swing.JTextField txtManagerContact;
    private javax.swing.JTextField txtManagerEmail;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
