/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.OrganizationsManage;

import Model.Hotel.Hotel;
import Model.LocalBusiness.LocalBusiness;
import Model.TransportAgency.TransportAgency;
import Model.Travel;
import Model.TravelAgency.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrutidixit
 */
public class ViewOrganizationDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Travel travel;
    private Hotel hotel;
    private LocalBusiness localBusiness;
    private String type;
    private TransportAgency transportAgency;
    private TravelAgency travelAgency;

    /**
     * Creates new form ViewOrganizationDeatilsJPanel
     */
    ViewOrganizationDetailsJPanel(JPanel userProcessContainer, Travel travel, Hotel hotel, String type) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.hotel = hotel;
        this.type = type;
        initComponents();
        populateInformation();
        btnSave.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtName.setEditable(false);
    }

    ViewOrganizationDetailsJPanel(JPanel userProcessContainer, Travel travel, LocalBusiness lb, String type) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.localBusiness = lb;
        this.type = type;
        initComponents();
        populateInformation();
        btnSave.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtName.setEditable(false);
    }

    ViewOrganizationDetailsJPanel(JPanel userProcessContainer, Travel travel, TransportAgency transportAgency, String type) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.transportAgency = transportAgency;
        this.type = type;
        initComponents();
        populateInformation();
        btnSave.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtName.setEditable(false);
    }    
    
        ViewOrganizationDetailsJPanel(JPanel userProcessContainer, Travel travel, TravelAgency travelAgency, String type) {
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.travelAgency = travelAgency;
        this.type = type;
        initComponents();
        populateInformation();
        btnSave.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtName.setEditable(false);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtHq = new javax.swing.JTextField();
        lblHq = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblManagerName = new javax.swing.JLabel();
        txtManagerEmail = new javax.swing.JTextField();
        lblManagerEmail = new javax.swing.JLabel();
        txtManagerContact = new javax.swing.JTextField();
        lblManagerContact = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        optionsType = new javax.swing.JComboBox<>();
        imgLogo = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 210, 40));

        txtDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 210, 40));

        lblDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblDescription.setText("Description:");
        add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        txtHq.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtHq, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 210, 40));

        lblHq.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblHq.setText("Location Headquarters:");
        add(lblHq, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        txtManagerName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 210, 40));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblName.setText("Organization Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        lblManagerName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerName.setText("Manager Name:");
        add(lblManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        txtManagerEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtManagerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerEmailActionPerformed(evt);
            }
        });
        add(txtManagerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 210, 40));

        lblManagerEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerEmail.setText("Manager Email:");
        add(lblManagerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        txtManagerContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtManagerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 210, 40));

        lblManagerContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerContact.setText("Manager Contact:");
        add(lblManagerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        lblLogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblLogo.setText("Logo:");
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, -1, -1));

        lblType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblType.setText("Type:");
        add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        optionsType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(optionsType, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 210, 40));

        imgLogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 158, 150));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, -1));

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtDescription.setEditable(true);
        txtHq.setEditable(true);
        txtManagerContact.setEditable(true);
        txtManagerEmail.setEditable(true);
        txtManagerName.setEditable(true);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(false);
        if (type.equals("Hotel")) {
            hotel.setBusinessDescription(txtDescription.getText());
            hotel.setHeadquarter(txtHq.getText());
            hotel.setManagerEmail(txtManagerEmail.getText());
            hotel.setManagerName(txtManagerName.getText());
            hotel.setManagerPhone(txtManagerContact.getText());
        }
        if (type.equals("Local Business")) {
            localBusiness.setBusinessDescription(txtDescription.getText());
            localBusiness.setHeadquarter(txtHq.getText());
            localBusiness.setManagerEmail(txtManagerEmail.getText());
            localBusiness.setManagerName(txtManagerName.getText());
            localBusiness.setManagerPhone(txtManagerContact.getText());
        }
        if ((type.equals("Air"))|| (type.equals("Road")) || (type.equals("Rail")) || (type.equals("Sea"))) {
            transportAgency.setBusinessDescription(txtDescription.getText());
            transportAgency.setHeadquarter(txtHq.getText());
            transportAgency.setManagerEmail(txtManagerEmail.getText());
            transportAgency.setManagerName(txtManagerName.getText());
            transportAgency.setManagerPhone(txtManagerContact.getText());
        }   
                if (type.equals("Travel Agency")) {
            travelAgency.setBusinessDescription(txtDescription.getText());
            travelAgency.setHeadquarter(txtHq.getText());
            travelAgency.setManagerEmail(txtManagerEmail.getText());
            travelAgency.setManagerName(txtManagerName.getText());
            travelAgency.setManagerPhone(txtManagerContact.getText());
        }
        JOptionPane.showMessageDialog(this, "Organization Details updated successfuly!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Component component = userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 2);
        if (component instanceof ViewOrganizationJPanel viewOrganizationJPanel) {
            viewOrganizationJPanel.populateTable();
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtManagerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManagerEmailActionPerformed

    private void populateInformation() {
        if (type.equals("Hotel")) {
            txtDescription.setText(hotel.getBusinessDescription());
            txtHq.setText(hotel.getHeadquarter());
            txtManagerContact.setText(hotel.getManagerPhone());
            txtManagerEmail.setText(hotel.getManagerEmail());
            txtManagerName.setText(hotel.getManagerName());
            txtName.setText(hotel.getBusinessName());
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement(hotel.getType());
            optionsType.setModel(model);
            optionsType.setEditable(false);
            imgLogo.setIcon(hotel.getLogoImage());
        }
        if (type.equals("Local Business")) {
            txtDescription.setText(localBusiness.getBusinessDescription());
            txtHq.setText(localBusiness.getHeadquarter());
            txtManagerContact.setText(localBusiness.getManagerPhone());
            txtManagerEmail.setText(localBusiness.getManagerEmail());
            txtManagerName.setText(localBusiness.getManagerName());
            txtName.setText(localBusiness.getBusinessName());
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement(localBusiness.getType());
            optionsType.setModel(model);
            optionsType.setEditable(false);
            imgLogo.setIcon(localBusiness.getLogoImage());
        }
        if (type.equals("Local Business")) {
            txtDescription.setText(localBusiness.getBusinessDescription());
            txtHq.setText(localBusiness.getHeadquarter());
            txtManagerContact.setText(localBusiness.getManagerPhone());
            txtManagerEmail.setText(localBusiness.getManagerEmail());
            txtManagerName.setText(localBusiness.getManagerName());
            txtName.setText(localBusiness.getBusinessName());
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement(localBusiness.getType());
            optionsType.setModel(model);
            optionsType.setEditable(false);
            imgLogo.setIcon(localBusiness.getLogoImage());
        }  
        if ((type.equals("Air"))|| (type.equals("Road")) || (type.equals("Rail")) || (type.equals("Sea"))){
            txtDescription.setText(transportAgency.getBusinessDescription());
            txtHq.setText(transportAgency.getHeadquarter());
            txtManagerContact.setText(transportAgency.getManagerPhone());
            txtManagerEmail.setText(transportAgency.getManagerEmail());
            txtManagerName.setText(transportAgency.getManagerName());
            txtName.setText(transportAgency.getBusinessName());
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement(transportAgency.getType());
            optionsType.setModel(model);
            optionsType.setEditable(false);
            imgLogo.setIcon(transportAgency.getLogoImage());            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblHq;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblManagerContact;
    private javax.swing.JLabel lblManagerEmail;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblType;
    private javax.swing.JComboBox<String> optionsType;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtHq;
    private javax.swing.JTextField txtManagerContact;
    private javax.swing.JTextField txtManagerEmail;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
