/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.Login;

import Model.Travel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author minal
 */
public class LandingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LandingJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    public LandingJPanel(JPanel userProcessContainer, Travel travel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.-Banner-1.png"))); // NOI18N
        jLabel1.setText("Welcome to TravelZen !");
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 1900));
        jLabel1.setMinimumSize(new java.awt.Dimension(2000, 1900));
        jLabel1.setPreferredSize(new java.awt.Dimension(2000, 1900));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -270, 700, 1000));

        LoginButton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(0, 0, 102));
        LoginButton.setText("Login");
        LoginButton.setBorder(new javax.swing.border.MatteBorder(null));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        CustomerLoginJPanel panel = new CustomerLoginJPanel(userProcessContainer, travel);
        userProcessContainer.add("CustomerLoginJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        /*AdminLoginJPanel panel = new AdminLoginJPanel(userProcessContainer, travel);
        userProcessContainer.add("AdminLoginJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
    }//GEN-LAST:event_LoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
