/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.TravelAgencyManagement;

import Model.Hotel.Hotel;
import Model.TransportAgency.Route;
import Model.TransportAgency.TransportAgency;
import Model.Travel;
import Model.TravelAgency.Plan;
import Model.TravelAgency.TravelAgency;
import java.awt.CardLayout;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrutidixit
 */
public class AddPlanJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Travel travel;
    private TravelAgency travelAgency;
    Route selectedRoute;
    Hotel selectedHotel ;

    /**
     * Creates new form AddPlanJPanel
     */

    AddPlanJPanel(JPanel userProcessContainer, Travel travel, TravelAgency travelAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.travelAgency = travelAgency;
        populateInfo();
      //  populateSugCost();
    }

    public void populateInfo() {
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Road");
        model.addElement("Rail");
        model.addElement("Sea");
        model.addElement("Air");
        optionsMode.setModel(model);
    }
    
//    public void populateSugCost(){
//        String mode = optionsMode.getSelectedItem().toString();
//        String startLocation = optionsStartLoc.getSelectedItem().toString();
//        String endLocation = optionsEndLoc.getSelectedItem().toString();
//        String selectHotel = optionsHotel.getSelectedItem().toString();
//                for(TransportAgency transportAgency : travel.getTrnsportAgencyDirectory().getTransporAgencyList()){
//            if (transportAgency.getMode().equals(mode)){
//                for (Route route : transportAgency.getRoutes()) {
//                    if(route.getStartLocation().equals(startLocation) && route.getEndLocation().equals(endLocation)){
//                       selectedRoute = route; 
//                       return;
//                }
//            }
//        }
//        }
//                
//                        
//        for(Hotel hot: travel.getHotelDirectory().getHotelList()){
//            if(hot.getBusinessName().equals(selectHotel)){
//                selectedHotel = hot;
//                return;
//            }
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlanName = new javax.swing.JTextField();
        optionsStartLoc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        optionsEndLoc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        optionsHotel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTotalNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTotCost = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        optionsMode = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Plan Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Start Location:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        txtPlanName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPlanName, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 97, 220, 40));

        optionsStartLoc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        optionsStartLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        optionsStartLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsStartLocActionPerformed(evt);
            }
        });
        add(optionsStartLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 220, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("End Location: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        optionsEndLoc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        optionsEndLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        optionsEndLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsEndLocActionPerformed(evt);
            }
        });
        add(optionsEndLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 220, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Hotel:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        optionsHotel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        optionsHotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        add(optionsHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 220, 40));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Total No of Days:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        txtTotalNo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtTotalNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 220, 40));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Total Cost:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        txtTotCost.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtTotCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 220, 40));

        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));

        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 88, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Mode:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        optionsMode.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        optionsMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        optionsMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsModeActionPerformed(evt);
            }
        });
        add(optionsMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 220, 40));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel6.setText("Add Plan");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtPlanName.setText("");
        txtTotCost.setText("");
        txtTotalNo.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String mode = optionsMode.getSelectedItem().toString();

        String planN = txtPlanName.getText();
        int totCost = Integer.parseInt(txtTotCost.getText());
        String totNo = txtTotalNo.getText();
        if (planN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        if(String.valueOf(optionsStartLoc.getSelectedItem()).equals("Select") || String.valueOf(optionsEndLoc.getSelectedItem()).equals("Select") || String.valueOf(optionsHotel.getSelectedItem()).equals("Select")){
            JOptionPane.showMessageDialog(this, "Please select valid option from dropdown processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Plan plan = new Plan();
        plan.setPlanId(planN);
        plan.setCost(totCost);
        for(TransportAgency transportAgency: travel.getTrnsportAgencyDirectory().getTransporAgencyList()){
            if (transportAgency.getMode().equals(mode)) {
                //System.out.print("HIIII");
                for (Route route : transportAgency.getRoutes()) {
                    if(String.valueOf(optionsStartLoc.getSelectedItem()).equals(route.getStartLocation()) && String.valueOf(optionsEndLoc.getSelectedItem()).equals(route.getEndLocation())){
                        selectedRoute = route;
                    }
                }
            }
        }
        for(Hotel h : travel.getHotelDirectory().getHotelList()){
            if(h.getBusinessName().equals(String.valueOf(optionsHotel.getSelectedItem()))){
                selectedHotel = h;
            }
        }
        plan.setRoute(selectedRoute);
        plan.setHotel(selectedHotel);
        travelAgency.getPlan().add(plan);
        JOptionPane.showMessageDialog(this, "Plan added successfuly!");
        txtPlanName.setText("");
        txtTotCost.setText("");
        txtTotalNo.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

        public static int generateVerificationCode() {
        Random random = new Random();
        return 500 + random.nextInt(1000); // Generates a random number between 100000 and 999999
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void optionsModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsModeActionPerformed
        // TODO add your handling code here:
        String mode = optionsMode.getSelectedItem().toString();
        //System.out.print(mode);
        
        DefaultComboBoxModel<String> start = new DefaultComboBoxModel<>();
         start.addElement("Select");
        for (TransportAgency transportAgency : travel.getTrnsportAgencyDirectory().getTransporAgencyList()) {
            if (transportAgency.getMode().equals(mode)) {
                //System.out.print("HIIII");
                for (Route route : transportAgency.getRoutes()) {
                    start.addElement(route.getStartLocation());
                }
            }
        }
        optionsStartLoc.setModel(start);
    }//GEN-LAST:event_optionsModeActionPerformed

    private void optionsStartLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsStartLocActionPerformed
        // TODO add your handling code here:
        String mode = optionsMode.getSelectedItem().toString();
        String startLocation = optionsStartLoc.getSelectedItem().toString();
        System.out.print(startLocation);
        
        DefaultComboBoxModel<String> end = new DefaultComboBoxModel<>();
        end.addElement("Select");
       
        for (TransportAgency transportAgency : travel.getTrnsportAgencyDirectory().getTransporAgencyList()) {
            if (transportAgency.getMode().equals(mode)) {
              for (Route route : transportAgency.getRoutes()) {
                    if(route.getStartLocation().equals(startLocation)){
                        end.addElement(route.getEndLocation());
                    }
                } 
            }
            }
        optionsEndLoc.setModel(end);        
    }//GEN-LAST:event_optionsStartLocActionPerformed

    private void optionsEndLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsEndLocActionPerformed
        // TODO add your handling code here:
        String endLocation = optionsEndLoc.getSelectedItem().toString();
        System.out.print(endLocation);
        
        DefaultComboBoxModel<String> optHotel = new DefaultComboBoxModel<>();
        optHotel.addElement("Select");
        for(Hotel hot: travel.getHotelDirectory().getHotelList()){
            if(hot.getHeadquarter().equals(endLocation)){
                optHotel.addElement(hot.getBusinessName());
            }
        }
        optionsHotel.setModel(optHotel);        
    }//GEN-LAST:event_optionsEndLocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> optionsEndLoc;
    private javax.swing.JComboBox<String> optionsHotel;
    private javax.swing.JComboBox<String> optionsMode;
    private javax.swing.JComboBox<String> optionsStartLoc;
    private javax.swing.JTextField txtPlanName;
    private javax.swing.JTextField txtTotCost;
    private javax.swing.JTextField txtTotalNo;
    // End of variables declaration//GEN-END:variables
}
