/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.Customer;

import Model.Hotel.Hotel;
import Model.Roles.Customer;
import Model.TransportAgency.TransportAgency;
import Model.Travel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minal
 */
public class CustomerHotelBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerHotelBookingJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    Customer customer;
    DefaultTableModel dtm;
    public CustomerHotelBookingJPanel(JPanel userProcessContainer, Travel travel, Customer customer) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.customer = customer;
        //Initialize the table model
        dtm = (DefaultTableModel) tblOrganization.getModel();
        populateTable();
    }
    private void populateTable() {
        dtm.setRowCount(0); // Clear existing rows
        DefaultTableModel dtm = (DefaultTableModel) tblOrganization.getModel();
        // Filter and add rows based on the type
        for (Hotel lb : travel.getHotelDirectory().getHotelList()) {
            String type = lb.getType();
            if (type.equals("Hotel")) {
                Object[] row = new Object[6];
                row[0] = lb; // Assuming getName() retrieves Organization Name
                row[1] = lb.getBusinessDescription();
                row[2] = lb.getType();
                row[3] = lb.getManagerName();
                row[4] = lb.getManagerPhone();
                row[5] = 600;
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Book Hotel");

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Organization Name", "Organization Description", "Organization Type", "Manager Name", "Manager Contact", "Cost"
            }
        ));
        jScrollPane1.setViewportView(tblOrganization);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblOrganization.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Plan from the list!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to book this plan?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            // Check if the customer has enough balance
            int cost = (int) tblOrganization.getValueAt(selectedRow, 5);

            if (cost > customer.getCurrency().getOrDefault("USD", 0.0)) {
                JOptionPane.showMessageDialog(this, "Insufficient USD funds. Please top up your account!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Deduct cost and confirm booking
            customer.getCurrency().put("USD", customer.getCurrency().get("USD") - cost);
            JOptionPane.showMessageDialog(this, "Travel Plan booked successfully!");

            populateTable(); // Refresh the table
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrganization;
    // End of variables declaration//GEN-END:variables
}
