/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.Customer;

import Model.Roles.Customer;
import Model.Travel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author minal
 */
public class CustomerJPanel extends javax.swing.JPanel {
     
    /**
     * Creates new form CustomerJPanel
     */
    private JPanel userProcessContainer;
    private Travel travel;
    Customer customer;
    private CustomerViewBookTripJPanel customerViewBookTripJPanel;
    
     public CustomerJPanel(JPanel userProcessContainer, Travel travel, Customer customer) {
        initComponents();    
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
       this.customer = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        CurrencyManagementjPanel = new javax.swing.JPanel();
        CurrencyManagementjLabel = new javax.swing.JLabel();
        ViewCurrentBookingjPanel = new javax.swing.JPanel();
        ViewCurrentBookingjLabel = new javax.swing.JLabel();
        BookaLocalTourGuidejPanel = new javax.swing.JPanel();
        BookaLocalTourGuidejLabel = new javax.swing.JLabel();
        BookATripJPanel = new javax.swing.JPanel();
        BookATripjLabel = new javax.swing.JLabel();
        HotelBookingjPanel = new javax.swing.JPanel();
        HotelBookingjLabel = new javax.swing.JLabel();
        ManageProfilejPanel = new javax.swing.JPanel();
        ManageProfilejLabel = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        lblWelcome1 = new javax.swing.JLabel();
        TravelBookingjPanel = new javax.swing.JPanel();
        TravelBookingjLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();

        jSplitPane1.setDividerSize(2);

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setMaximumSize(new java.awt.Dimension(400, 2147483647));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CurrencyManagementjPanel.setBackground(new java.awt.Color(85, 65, 118));
        CurrencyManagementjPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CurrencyManagementjPanelMouseClicked(evt);
            }
        });

        CurrencyManagementjLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        CurrencyManagementjLabel.setForeground(new java.awt.Color(255, 255, 255));
        CurrencyManagementjLabel.setText("Currency Management");

        javax.swing.GroupLayout CurrencyManagementjPanelLayout = new javax.swing.GroupLayout(CurrencyManagementjPanel);
        CurrencyManagementjPanel.setLayout(CurrencyManagementjPanelLayout);
        CurrencyManagementjPanelLayout.setHorizontalGroup(
            CurrencyManagementjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyManagementjPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(CurrencyManagementjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CurrencyManagementjPanelLayout.setVerticalGroup(
            CurrencyManagementjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurrencyManagementjPanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(CurrencyManagementjLabel)
                .addGap(21, 21, 21))
        );

        jPanel2.add(CurrencyManagementjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 360, 50));

        ViewCurrentBookingjPanel.setBackground(new java.awt.Color(85, 65, 118));
        ViewCurrentBookingjPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCurrentBookingjPanelMouseClicked(evt);
            }
        });

        ViewCurrentBookingjLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        ViewCurrentBookingjLabel.setForeground(new java.awt.Color(255, 255, 255));
        ViewCurrentBookingjLabel.setText("View Current Booking");

        javax.swing.GroupLayout ViewCurrentBookingjPanelLayout = new javax.swing.GroupLayout(ViewCurrentBookingjPanel);
        ViewCurrentBookingjPanel.setLayout(ViewCurrentBookingjPanelLayout);
        ViewCurrentBookingjPanelLayout.setHorizontalGroup(
            ViewCurrentBookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewCurrentBookingjPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(ViewCurrentBookingjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewCurrentBookingjPanelLayout.setVerticalGroup(
            ViewCurrentBookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewCurrentBookingjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewCurrentBookingjLabel)
                .addGap(20, 20, 20))
        );

        jPanel2.add(ViewCurrentBookingjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 360, 40));

        BookaLocalTourGuidejPanel.setBackground(new java.awt.Color(85, 65, 118));
        BookaLocalTourGuidejPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookaLocalTourGuidejPanelMouseClicked(evt);
            }
        });

        BookaLocalTourGuidejLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        BookaLocalTourGuidejLabel.setForeground(new java.awt.Color(255, 255, 255));
        BookaLocalTourGuidejLabel.setText("Book a Local Tour Guide");

        javax.swing.GroupLayout BookaLocalTourGuidejPanelLayout = new javax.swing.GroupLayout(BookaLocalTourGuidejPanel);
        BookaLocalTourGuidejPanel.setLayout(BookaLocalTourGuidejPanelLayout);
        BookaLocalTourGuidejPanelLayout.setHorizontalGroup(
            BookaLocalTourGuidejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookaLocalTourGuidejPanelLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(BookaLocalTourGuidejLabel)
                .addGap(79, 79, 79))
        );
        BookaLocalTourGuidejPanelLayout.setVerticalGroup(
            BookaLocalTourGuidejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookaLocalTourGuidejPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(BookaLocalTourGuidejLabel)
                .addGap(20, 20, 20))
        );

        jPanel2.add(BookaLocalTourGuidejPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 360, -1));

        BookATripJPanel.setBackground(new java.awt.Color(85, 65, 118));
        BookATripJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookATripJPanelMouseClicked(evt);
            }
        });

        BookATripjLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        BookATripjLabel.setForeground(new java.awt.Color(255, 255, 255));
        BookATripjLabel.setText("Book a Trip");

        javax.swing.GroupLayout BookATripJPanelLayout = new javax.swing.GroupLayout(BookATripJPanel);
        BookATripJPanel.setLayout(BookATripJPanelLayout);
        BookATripJPanelLayout.setHorizontalGroup(
            BookATripJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookATripJPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(BookATripjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BookATripJPanelLayout.setVerticalGroup(
            BookATripJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookATripJPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(BookATripjLabel)
                .addGap(17, 17, 17))
        );

        jPanel2.add(BookATripJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 360, 50));

        HotelBookingjPanel.setBackground(new java.awt.Color(85, 65, 118));
        HotelBookingjPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HotelBookingjPanelMouseClicked(evt);
            }
        });

        HotelBookingjLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        HotelBookingjLabel.setForeground(new java.awt.Color(255, 255, 255));
        HotelBookingjLabel.setText("Hotel Booking");

        javax.swing.GroupLayout HotelBookingjPanelLayout = new javax.swing.GroupLayout(HotelBookingjPanel);
        HotelBookingjPanel.setLayout(HotelBookingjPanelLayout);
        HotelBookingjPanelLayout.setHorizontalGroup(
            HotelBookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HotelBookingjPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(HotelBookingjLabel)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        HotelBookingjPanelLayout.setVerticalGroup(
            HotelBookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HotelBookingjPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(HotelBookingjLabel)
                .addGap(20, 20, 20))
        );

        jPanel2.add(HotelBookingjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 360, 50));

        ManageProfilejPanel.setBackground(new java.awt.Color(85, 65, 118));
        ManageProfilejPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageProfilejPanelMouseClicked(evt);
            }
        });

        ManageProfilejLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        ManageProfilejLabel.setForeground(new java.awt.Color(255, 255, 255));
        ManageProfilejLabel.setText("Manage Profile");

        javax.swing.GroupLayout ManageProfilejPanelLayout = new javax.swing.GroupLayout(ManageProfilejPanel);
        ManageProfilejPanel.setLayout(ManageProfilejPanelLayout);
        ManageProfilejPanelLayout.setHorizontalGroup(
            ManageProfilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageProfilejPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(ManageProfilejLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ManageProfilejPanelLayout.setVerticalGroup(
            ManageProfilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageProfilejPanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(ManageProfilejLabel)
                .addGap(21, 21, 21))
        );

        jPanel2.add(ManageProfilejPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 360, 50));

        btnBack3.setText("Back");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        lblWelcome1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome1.setText("Hi Customer");
        jPanel2.add(lblWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, -1));

        TravelBookingjPanel.setBackground(new java.awt.Color(85, 65, 118));
        TravelBookingjPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TravelBookingjPanelMouseClicked(evt);
            }
        });

        TravelBookingjLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        TravelBookingjLabel.setForeground(new java.awt.Color(255, 255, 255));
        TravelBookingjLabel.setText("Travel Booking");

        javax.swing.GroupLayout TravelBookingjPanelLayout = new javax.swing.GroupLayout(TravelBookingjPanel);
        TravelBookingjPanel.setLayout(TravelBookingjPanelLayout);
        TravelBookingjPanelLayout.setHorizontalGroup(
            TravelBookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TravelBookingjPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(TravelBookingjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TravelBookingjPanelLayout.setVerticalGroup(
            TravelBookingjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TravelBookingjPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(TravelBookingjLabel)
                .addGap(20, 20, 20))
        );

        jPanel2.add(TravelBookingjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 360, 50));

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1878, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2240, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CurrencyManagementjPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrencyManagementjPanelMouseClicked
        // TODO add your handling code here:
        CustomerCurrencyJPanel panel = new CustomerCurrencyJPanel(userProcessContainer, travel, customer);
        jSplitPane1.setRightComponent(panel);
        setColor(CurrencyManagementjPanel);
        resetColor(ViewCurrentBookingjPanel);
        resetColor(BookaLocalTourGuidejPanel);
        resetColor(TravelBookingjPanel);
        resetColor(BookATripJPanel);
        resetColor(HotelBookingjPanel);
        resetColor(ManageProfilejPanel);
    }//GEN-LAST:event_CurrencyManagementjPanelMouseClicked

    private void ViewCurrentBookingjPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCurrentBookingjPanelMouseClicked
        // TODO add your handling code here:
        CustomerViewBookTripJPanel panel = new CustomerViewBookTripJPanel(userProcessContainer, travel, customer);
        jSplitPane1.setRightComponent(panel);
        setColor(ViewCurrentBookingjPanel );
        resetColor(CurrencyManagementjPanel);
        resetColor(BookaLocalTourGuidejPanel);
        resetColor(TravelBookingjPanel);
        resetColor(BookATripJPanel);
        resetColor(HotelBookingjPanel);
        resetColor(ManageProfilejPanel);

    }//GEN-LAST:event_ViewCurrentBookingjPanelMouseClicked

    private void BookaLocalTourGuidejPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookaLocalTourGuidejPanelMouseClicked
        // TODO add your handling code here:
        CustomerAddBookingLocalBusinessJPanel panel = new CustomerAddBookingLocalBusinessJPanel(userProcessContainer, travel, customer);
        jSplitPane1.setRightComponent(panel);
        setColor(BookaLocalTourGuidejPanel );
        resetColor(ViewCurrentBookingjPanel);
        resetColor(CurrencyManagementjPanel);
        resetColor(TravelBookingjPanel);
        resetColor(BookATripJPanel);
        resetColor(HotelBookingjPanel);
        resetColor(ManageProfilejPanel);
    }//GEN-LAST:event_BookaLocalTourGuidejPanelMouseClicked

    private void BookATripJPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookATripJPanelMouseClicked
        CustomerBookTripJPanel panel = new CustomerBookTripJPanel(userProcessContainer, travel, customer);
        jSplitPane1.setRightComponent(panel);
        setColor( BookATripJPanel);
        resetColor(ViewCurrentBookingjPanel);
        resetColor(BookaLocalTourGuidejPanel);
        resetColor(TravelBookingjPanel);
        resetColor(CurrencyManagementjPanel);
        resetColor(HotelBookingjPanel);
        resetColor(ManageProfilejPanel);
    }//GEN-LAST:event_BookATripJPanelMouseClicked

    private void ManageProfilejPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProfilejPanelMouseClicked
        // TODO add your handling code here:
        CustomerProfileJPanel panel = new CustomerProfileJPanel(userProcessContainer, travel, customer);
        jSplitPane1.setRightComponent(panel);
        setColor(ManageProfilejPanel);
        resetColor(ViewCurrentBookingjPanel);
        resetColor(BookaLocalTourGuidejPanel);
        resetColor(TravelBookingjPanel);
        resetColor(BookATripJPanel);
        resetColor(HotelBookingjPanel);
        resetColor(CurrencyManagementjPanel);
    }//GEN-LAST:event_ManageProfilejPanelMouseClicked

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void HotelBookingjPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HotelBookingjPanelMouseClicked
        // TODO add your handling code here:
        CustomerHotelBookingJPanel panel = new CustomerHotelBookingJPanel(userProcessContainer, travel, customer);
        jSplitPane1.setRightComponent(panel);
        setColor(HotelBookingjPanel);
        resetColor(ViewCurrentBookingjPanel);
        resetColor(BookaLocalTourGuidejPanel);
        resetColor(TravelBookingjPanel);
        resetColor(BookATripJPanel);
        resetColor(ManageProfilejPanel);
        resetColor(CurrencyManagementjPanel);
    }//GEN-LAST:event_HotelBookingjPanelMouseClicked

    private void TravelBookingjPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TravelBookingjPanelMouseClicked
        // TODO add your handling code here:
        CustomerTravelBookingJPanel panel = new CustomerTravelBookingJPanel(userProcessContainer, travel, customer);
        jSplitPane1.setRightComponent(panel);
        setColor(TravelBookingjPanel);
        resetColor(ViewCurrentBookingjPanel);
        resetColor(BookaLocalTourGuidejPanel);
        resetColor(HotelBookingjPanel);
        resetColor(BookATripJPanel);
        resetColor(ManageProfilejPanel);
        resetColor(CurrencyManagementjPanel);
    }//GEN-LAST:event_TravelBookingjPanelMouseClicked
void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookATripJPanel;
    private javax.swing.JLabel BookATripjLabel;
    private javax.swing.JLabel BookaLocalTourGuidejLabel;
    private javax.swing.JPanel BookaLocalTourGuidejPanel;
    private javax.swing.JLabel CurrencyManagementjLabel;
    private javax.swing.JPanel CurrencyManagementjPanel;
    private javax.swing.JLabel HotelBookingjLabel;
    private javax.swing.JPanel HotelBookingjPanel;
    private javax.swing.JLabel ManageProfilejLabel;
    private javax.swing.JPanel ManageProfilejPanel;
    private javax.swing.JLabel TravelBookingjLabel;
    private javax.swing.JPanel TravelBookingjPanel;
    private javax.swing.JLabel ViewCurrentBookingjLabel;
    private javax.swing.JPanel ViewCurrentBookingjPanel;
    private javax.swing.JButton btnBack3;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcome1;
    // End of variables declaration//GEN-END:variables
}
