/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.TransportAgencyManagement;


import Model.TransportAgency.Route;
import Model.TransportAgency.TransportAgency;
import Model.Travel;
import static Utilities.Validations.validateName;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrutidixit
 */
public class AddRoutesJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Travel travel;
    private TransportAgency transportAgency;
    ArrayList<Route> routes = new ArrayList();
    /**
     * Creates new form AddRoutesJPanel
     */

    AddRoutesJPanel(JPanel userProcessContainer, Travel travel, TransportAgency transportAgency) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.transportAgency = transportAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStartLoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRouteId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEndLoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        txtPlaneNo = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Route Id:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        txtStartLoc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtStartLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 250, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Start Location:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        txtRouteId.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtRouteId, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 250, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("End Location:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        txtEndLoc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtEndLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 250, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Capacity:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Plane Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Price:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        txtCapacity.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 250, 40));

        txtPlaneNo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPlaneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 250, 40));

        txtPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 250, 40));

        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, -1, -1));

        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, -1, -1));

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 88, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtCapacity.setText("");
        txtEndLoc.setText("");
        txtPlaneNo.setText("");
        txtPrice.setText("");
        txtRouteId.setText("");
        txtStartLoc.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String routeId = txtRouteId.getText();
        String startLoc = txtStartLoc.getText();
        String endLoc = txtEndLoc.getText();
        String capacity = txtCapacity.getText();
        String planeNo = txtPlaneNo.getText();
        int price = Integer.parseInt(txtPrice.getText());
        
        if(routeId.isEmpty() || startLoc.isEmpty() || endLoc.isEmpty() || capacity.isEmpty() || planeNo.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Route route = new Route();
        route.setCapacity(capacity);
        route.setEndLocation(endLoc);
        route.setPlaneName(planeNo);
        route.setRouteId(routeId);
        route.setStartLocation(startLoc);
        route.setPrice(price);
        routes.add(route);
        transportAgency.setRoutes(routes);
JOptionPane.showMessageDialog(this, "Route added successfuly!");
        txtCapacity.setText("");
        txtEndLoc.setText("");
        txtPlaneNo.setText("");
        txtPrice.setText("");
        txtRouteId.setText("");
        txtStartLoc.setText("");

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtEndLoc;
    private javax.swing.JTextField txtPlaneNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRouteId;
    private javax.swing.JTextField txtStartLoc;
    // End of variables declaration//GEN-END:variables
}
