/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.TransportAgencyManagement;

import Model.TransportAgency.TransportAgency;
import Model.Travel;
import static Utilities.Validations.validateEmail;
import static Utilities.Validations.validateName;
import static Utilities.Validations.validatePassword;
import static Utilities.Validations.validatePhone;
import static Utilities.Validations.validateUsername;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrutidixit
 */
public class ManageProfileJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Travel travel;
    private TransportAgency transportAgency;
    private String username;
        private final JFileChooser fileChooser = new JFileChooser();
    ImageIcon logoImage;
    /**
     * Creates new form ManageProfileJPanel
     */


    public ManageProfileJPanel(JPanel userProcessContainer, Travel travel, TransportAgency transportAgency, String username) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.transportAgency = transportAgency;
        this.username = username;
        btnSave.setEnabled(false);
        btnAttach.setEnabled(false);
        btnRemove.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(false);
        txtManagerContact.setEditable(false);
        txtManagerEmail.setEditable(false);
        txtManagerName.setEditable(false);
        txtPassword.setEditable(false);
        populateInfo();
    }
    
    public void populateInfo(){
        txtDescription.setText(transportAgency.getBusinessDescription());
        txtHq.setText(transportAgency.getHeadquarter());
        txtManagerContact.setText(transportAgency.getManagerPhone());
        txtManagerEmail.setText(transportAgency.getManagerEmail());
        txtManagerName.setText(transportAgency.getManagerName());
        txtName.setText(transportAgency.getBusinessName());
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement(transportAgency.getType());
        optionsType.setModel(model);
        imgLogo.setIcon(transportAgency.getLogoImage());
        txtUsername.setText(username);
        txtPassword.setText(transportAgency.getLoginCredentials().get(username));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManagerContact = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        optionsType = new javax.swing.JComboBox<>();
        imgLogo = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtHq = new javax.swing.JTextField();
        lblHq = new javax.swing.JLabel();
        txtManagerName = new javax.swing.JTextField();
        lblManagerName = new javax.swing.JLabel();
        txtManagerEmail = new javax.swing.JTextField();
        lblManagerEmail = new javax.swing.JLabel();
        txtManagerContact = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManagerContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerContact.setText("Manager Contact:");
        add(lblManagerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, -1, -1));

        lblLogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblLogo.setText("Logo:");
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, -1, -1));

        lblType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblType.setText("Type:");
        add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        optionsType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(optionsType, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 220, 40));

        imgLogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        imgLogo.setText("<No Image>");
        imgLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 158, 150));

        btnAttach.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAttach.setText("Attach");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });
        add(btnAttach, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 73, -1));

        lblName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        btnRemove.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, -1, -1));

        lblUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, 70, -1));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 220, 40));

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 220, 40));

        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 220, 40));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        txtDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 220, 40));

        lblDescription.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblDescription.setText("Description:");
        add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        txtHq.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtHq, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 220, 40));

        lblHq.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblHq.setText("Location Headquarters:");
        add(lblHq, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        txtManagerName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 220, 40));

        lblManagerName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerName.setText("Manager Name:");
        add(lblManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        txtManagerEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtManagerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 220, 40));

        lblManagerEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblManagerEmail.setText("Manager Email:");
        add(lblManagerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        txtManagerContact.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtManagerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 220, 40));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String oName = txtName.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String description = txtDescription.getText();
        String headquarters = txtHq.getText();
        String mName = txtManagerName.getText();
        String mEmail = txtManagerEmail.getText();
        String mContact = txtManagerContact.getText();
        String type = optionsType.getSelectedItem().toString();
        btnAttach.setEnabled(true);
        btnRemove.setEnabled(true);
        
        if(oName.isEmpty() || username.isEmpty() || password.isEmpty() || description.isEmpty() || headquarters.isEmpty() || mName.isEmpty() || mEmail.isEmpty() || mContact.isEmpty() || type.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(validateName(mName)){
            JOptionPane.showMessageDialog(this, "Name should be between 5 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(validateUsername(username)){
            JOptionPane.showMessageDialog(this, "Username should be between 5 to 15 length and should not contain any special characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(validatePhone(mContact)){
            JOptionPane.showMessageDialog(this, "Please verify if Phone number is in correct format \"(000) 000-0000\"", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(validateEmail(mEmail)){
            JOptionPane.showMessageDialog(this, "Please verify if email is in correct format \"youremail@xxx.xxx\"", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(validatePassword(password)){
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one digit.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


        Map<String, String> loginCredentials = new HashMap<>();
        loginCredentials.put(username, password);

        for(TransportAgency transportAgency: travel.getTrnsportAgencyDirectory().getTransporAgencyList()){
            if(transportAgency.getBusinessName().equals(oName) && transportAgency.getType().equals(type)){
                transportAgency.setBusinessDescription(description);
                transportAgency.setBusinessName(oName);
                transportAgency.setHeadquarter(headquarters);
                transportAgency.setLoginCredentials(loginCredentials);
                transportAgency.setLogoImage(logoImage);
                transportAgency.setManagerEmail(mEmail);
                transportAgency.setManagerName(mName);
                transportAgency.setManagerPhone(mContact);
            }
        }
        JOptionPane.showMessageDialog(this, "Organization Details Updated successfuly!");
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtDescription.setText("");
        txtHq.setText("");
        txtManagerName.setText("");
        txtManagerEmail.setText("");
        txtManagerContact.setText("");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);

        if(returnVal == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            URL url;
            try{
                url = file.toURI().toURL();
                logoImage = new ImageIcon(url);
                logoImage = new ImageIcon(logoImage.getImage().getScaledInstance(150,150,Image.SCALE_SMOOTH));
                imgLogo.setIcon(logoImage);
            }catch(MalformedURLException ex){
                java.util.logging.Logger.getLogger(this.getName()).log(java.util.logging.Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        logoImage = null;
        imgLogo.setIcon(logoImage);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnAttach.setEnabled(true);
        btnRemove.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtDescription.setEditable(false);
        txtHq.setEditable(true);
        txtManagerContact.setEditable(true);
        txtManagerEmail.setEditable(true);
        txtManagerName.setEditable(true);
        txtPassword.setEditable(true);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblHq;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblManagerContact;
    private javax.swing.JLabel lblManagerEmail;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JComboBox<String> optionsType;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtHq;
    private javax.swing.JTextField txtManagerContact;
    private javax.swing.JTextField txtManagerEmail;
    private javax.swing.JTextField txtManagerName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
