/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.WorkAreas.TransportAgencyManagement;

import Model.TransportAgency.Route;
import Model.Travel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrutidixit
 */
public class ViewRouteDetailsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Travel travel;
    Route route;
    /**
     * Creates new form ViewRouteDetailsJPanel
     */

    ViewRouteDetailsJPanel(JPanel userProcessContainer, Travel travel, Route route) {
initComponents();
        this.userProcessContainer = userProcessContainer;
        this.travel = travel;
        this.route = route;
                btnSave.setEnabled(false);
        populateInfo();
    }
    
        private void populateInfo(){
txtCapacity.setText(route.getCapacity());
txtEndLoc.setText(route.getEndLocation());
txtPlaneNo.setText(route.getPlaneName());
txtPrice.setText(String.valueOf(route.getPrice()));
txtRouteId.setText(route.getRouteId());
txtStartLoc.setText(route.getStartLocation());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtRouteId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEndLoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        txtPlaneNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtStartLoc = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Start Location:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        txtRouteId.setEditable(false);
        txtRouteId.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtRouteId, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 27, 240, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("End Location:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        txtEndLoc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtEndLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 240, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Capacity:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Plane Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Price:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        txtCapacity.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 240, 40));

        txtPlaneNo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPlaneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 240, 40));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Route Id:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        txtPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 240, 40));

        txtStartLoc.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add(txtStartLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 240, 40));

        btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, -1, -1));

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, -1, -1));

        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 380, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(false);
        String startLoc = txtStartLoc.getText();
        String endLoc = txtEndLoc.getText();
        String capacity = txtCapacity.getText();
        String planeNo = txtPlaneNo.getText();
        int price = Integer.parseInt(txtPrice.getText());
        if(startLoc.isEmpty() || endLoc.isEmpty() || capacity.isEmpty() || planeNo.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please check if all fields are filled before processing", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        route.setCapacity(capacity);
        route.setEndLocation(endLoc);
        route.setPlaneName(planeNo);
        route.setStartLocation(startLoc);
        route.setPrice(price);
        JOptionPane.showMessageDialog(this, "Organization Details updated successfuly!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Component component = userProcessContainer.getComponent(userProcessContainer.getComponentCount() - 2);
        if(component instanceof ManageRoutesJPanel manageRoutesJPanel) {
            manageRoutesJPanel.populateTable();
        }
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtEndLoc;
    private javax.swing.JTextField txtPlaneNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRouteId;
    private javax.swing.JTextField txtStartLoc;
    // End of variables declaration//GEN-END:variables
}
